version: '3'

services:
    back-end:
        container_name: dinmo_backend
        restart: always
        build:
          context: .
          dockerfile: .docker/Dockerfile.backend
        volumes:
          - ./db:/app/db 
        ports:
          - 8000:8000
        environment:
          - TEST=false