FROM python:3.10.6-bullseye

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY main.py main.py
COPY config.py config.py
COPY api api
COPY db db

ENTRYPOINT [ "python", "main.py" ]